language: java
jdk: openjdk8

addons:
  sonarcloud:
    organization: "alirezaasadi2018"

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'